nodeLinker: pnp
enableGlobalCache: false

# packageExtensions:
#   "@sentry/wizard@*":
#     dependencies:
#       "recast": "*"
#       "ast-types": "*"
#   "@opentelemetry/instrumentation-http@*":
#     dependencies:
#       "@opentelemetry/api": "*"

yarnPath: .yarn/releases/yarn-4.3.0.cjs
